// To parse this JSON data, do
//
//     final character = characterFromJson(jsonString);


// Generated by https://app.quicktype.io/ from the following character JSON:

//{
//  "_embedded" : {
//    "characters" : [ {
//      "character" : "的",
//      "frequencyRank" : 1,
//      "frequency" : 7922684,
//      "frequencyPercentage" : 4.09,
//      "cumulativePercentage" : 4.09,
//      "pinyin" : "de/di2/di4",
//      "englishTranslation" : "(possessive particle)/of, really and truly, aim/clear",
//      "_links" : {
//        "self" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998c"
//        },
//        "character" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998c"
//        }
//      }
//    }, {
//      "character" : "一",
//      "frequencyRank" : 2,
//      "frequency" : 3050722,
//      "frequencyPercentage" : 1.58,
//      "cumulativePercentage" : 5.67,
//      "pinyin" : "yi1",
//      "englishTranslation" : "one/1/single/a(n)",
//      "_links" : {
//        "self" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998d"
//        },
//        "character" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998d"
//        }
//      }
//    }, {
//      "character" : "是",
//      "frequencyRank" : 3,
//      "frequency" : 2615490,
//      "frequencyPercentage" : 1.34,
//      "cumulativePercentage" : 7.02,
//      "pinyin" : "shi4",
//      "englishTranslation" : "is/are/am/yes/to be",
//      "_links" : {
//        "self" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998e"
//        },
//        "character" : {
//          "href" : "http://localhost:8080/characters/5eebd3d4017d06919af6998e"
//        }
//      }
//    } ]
//  },
//  "_links" : {
//    "first" : {
//      "href" : "http://localhost:8080/characters?page=0&size=3&sort=frequencyRank,asc"
//    },
//    "self" : {
//      "href" : "http://localhost:8080/characters"
//    },
//    "next" : {
//      "href" : "http://localhost:8080/characters?page=1&size=3&sort=frequencyRank,asc"
//    },
//    "last" : {
//      "href" : "http://localhost:8080/characters?page=3310&size=3&sort=frequencyRank,asc"
//    },
//    "profile" : {
//      "href" : "http://localhost:8080/profile/characters"
//    },
//    "search" : {
//      "href" : "http://localhost:8080/characters/search"
//    }
//  },
//  "page" : {
//    "size" : 3,
//    "totalElements" : 9933,
//    "totalPages" : 3311,
//    "number" : 0
//  }
//}

import 'dart:convert';

Character characterFromJson(String str) => Character.fromJson(json.decode(str));

String characterToJson(Character data) => json.encode(data.toJson());

class Character {
  Character({
    this.embedded,
    this.links,
    this.page,
  });

  Embedded embedded;
  CharacterLinksClass links;
  Page page;

  factory Character.fromJson(Map<String, dynamic> json) => Character(
    embedded: Embedded.fromJson(json["_embedded"]),
    links: CharacterLinksClass.fromJson(json["_links"]),
    page: Page.fromJson(json["page"]),
  );

  Map<String, dynamic> toJson() => {
    "_embedded": embedded.toJson(),
    "_links": links.toJson(),
    "page": page.toJson(),
  };
}

class Embedded {
  Embedded({
    this.characters,
  });

  List<CharacterElement> characters;

  factory Embedded.fromJson(Map<String, dynamic> json) => Embedded(
    characters: List<CharacterElement>.from(json["characters"].map((x) => CharacterElement.fromJson(x))),
  );

  Map<String, dynamic> toJson() => {
    "characters": List<dynamic>.from(characters.map((x) => x.toJson())),
  };
}

class CharacterElement {
  CharacterElement({
    this.character,
    this.frequencyRank,
    this.frequency,
    this.frequencyPercentage,
    this.cumulativePercentage,
    this.pinyin,
    this.englishTranslation,
    this.links,
  });

  String character;
  int frequencyRank;
  int frequency;
  double frequencyPercentage;
  double cumulativePercentage;
  String pinyin;
  String englishTranslation;
  CharacterLinks links;

  factory CharacterElement.fromJson(Map<String, dynamic> json) => CharacterElement(
    character: json["character"],
    frequencyRank: json["frequencyRank"],
    frequency: json["frequency"],
    frequencyPercentage: json["frequencyPercentage"].toDouble(),
    cumulativePercentage: json["cumulativePercentage"].toDouble(),
    pinyin: json["pinyin"],
    englishTranslation: json["englishTranslation"],
    links: CharacterLinks.fromJson(json["_links"]),
  );

  Map<String, dynamic> toJson() => {
    "character": character,
    "frequencyRank": frequencyRank,
    "frequency": frequency,
    "frequencyPercentage": frequencyPercentage,
    "cumulativePercentage": cumulativePercentage,
    "pinyin": pinyin,
    "englishTranslation": englishTranslation,
    "_links": links.toJson(),
  };
}

class CharacterLinks {
  CharacterLinks({
    this.self,
    this.character,
  });

  First self;
  First character;

  factory CharacterLinks.fromJson(Map<String, dynamic> json) => CharacterLinks(
    self: First.fromJson(json["self"]),
    character: First.fromJson(json["character"]),
  );

  Map<String, dynamic> toJson() => {
    "self": self.toJson(),
    "character": character.toJson(),
  };
}

class First {
  First({
    this.href,
  });

  String href;

  factory First.fromJson(Map<String, dynamic> json) => First(
    href: json["href"],
  );

  Map<String, dynamic> toJson() => {
    "href": href,
  };
}

class CharacterLinksClass {
  CharacterLinksClass({
    this.first,
    this.self,
    this.next,
    this.last,
    this.profile,
    this.search,
  });

  First first;
  First self;
  First next;
  First last;
  First profile;
  First search;

  factory CharacterLinksClass.fromJson(Map<String, dynamic> json) => CharacterLinksClass(
    first: First.fromJson(json["first"]),
    self: First.fromJson(json["self"]),
    next: First.fromJson(json["next"]),
    last: First.fromJson(json["last"]),
    profile: First.fromJson(json["profile"]),
    search: First.fromJson(json["search"]),
  );

  Map<String, dynamic> toJson() => {
    "first": first.toJson(),
    "self": self.toJson(),
    "next": next.toJson(),
    "last": last.toJson(),
    "profile": profile.toJson(),
    "search": search.toJson(),
  };
}

class Page {
  Page({
    this.size,
    this.totalElements,
    this.totalPages,
    this.number,
  });

  int size;
  int totalElements;
  int totalPages;
  int number;

  factory Page.fromJson(Map<String, dynamic> json) => Page(
    size: json["size"],
    totalElements: json["totalElements"],
    totalPages: json["totalPages"],
    number: json["number"],
  );

  Map<String, dynamic> toJson() => {
    "size": size,
    "totalElements": totalElements,
    "totalPages": totalPages,
    "number": number,
  };
}


